### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by poblabs** [poblabs/weewx-belchertown#120]
Right now the following items need to be completed before 1.0 can be released.

- [x] moon phase translations
- [x] test chart decimals and timezone offsets
- [x] test non-mqtt pages in light, dark and on mobile (non-mqtt pages do not support auto theme)
- [x] ordinal compass translations
- [x] move time_charts_tooltip_* to graphs.conf as a per-graph-group option
- [x] rename JsonGenerator to GraphGenerator to not collide with future weewx JSON Generator
- [x] add numberFormat override to observations which may need special attention to decimal, decimalPoint and thousandsSep

**Comment by slvrscoobie** [comment]
Not sure if this is a good place to add this, but was wondering on point 1; Is there any plan to add any of the sun informations as well, like the weather34 template? I assume maybe that might be a 1.1 or even 2.0 release idea?

**Comment by poblabs** [comment]
weewx does have extensive sun information available if you have pyephem installed. I don't want to copy weather34's template (Hi Brian), but I can [add more weewx almanac tags](http://weewx.com/docs/customizing.htm#Almanac) to the skin. The question is, where?

**Comment by poblabs** [comment]
@slvrscoobie FYI - I've added the detailed Almanac information in the latest commit. It's borrowed from the Seasons skin, but it contains everything weewx is aware of if you have pyephem installed.

**Comment by slvrscoobie** [comment]
Thanks!! I'll take a look :)

**Comment by HoracioDos** [comment]
Hello Pat.
I know that the almanac is a work in progress. I added this to the style sheet.
```
.modal-title {
    font-size: 25px;
    text-align: center;
}
```
Then I removed "Celestial Information" title and I fixed some small things. It looks like this now.
![almanac](https://user-images.githubusercontent.com/4549674/58148859-c6fc1c00-7c36-11e9-85d2-1d4ed27c0b87.png)
